package com.seventeen17.commerceagent.approval;

import com.seventeen17.commerceagent.eligibility.AllowedAction;
import com.seventeen17.commerceagent.security.CommercePrincipal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

/**
 * Authoritative human approval for one proposed after-sales action.
 *
 * <p>An approval is deliberately not a boolean. It binds one decision to the exact
 * {@code (run, order, action, amount)} tuple that was presented to the approver. A later write may
 * use this row only if the tuple still matches and the status is {@link ApprovalStatus#APPROVED}.
 *
 * <p>The entity owns the lifecycle invariant: only {@code PENDING} may transition, and a terminal
 * decision can never be rewritten. HTTP authorization is enforced again by the service/controller
 * boundary in T052; the explicit principal check here is defense in depth and makes the T049
 * contract executable without an HTTP server.
 */
@Entity
@Table(name = "approval_requests")
public class ApprovalRequest {

    @Id
    @Column(name = "id", length = 64, nullable = false, updatable = false)
    private String id;

    @Column(name = "run_id", length = 64, nullable = false, updatable = false)
    private String runId;

    @Column(name = "order_id", length = 64, nullable = false, updatable = false)
    private String orderId;

    @Column(name = "user_id", length = 64, nullable = false, updatable = false)
    private String userId;

    @Enumerated(EnumType.STRING)
    @Column(name = "action", length = 32, nullable = false, updatable = false)
    private AllowedAction action;

    @Column(name = "amount", precision = 19, scale = 2, updatable = false)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 32, nullable = false)
    private ApprovalStatus status;

    @Column(name = "eligibility_rule_code", length = 100, nullable = false, updatable = false)
    private String eligibilityRuleCode;

    @Column(name = "reason_code", length = 100, nullable = false, updatable = false)
    private String reasonCode;

    @Column(name = "decided_by", length = 64)
    private String decidedBy;

    @Column(name = "decided_at")
    private Instant decidedAt;

    @Column(name = "expires_at", nullable = false, updatable = false)
    private Instant expiresAt;

    @Generated(event = EventType.INSERT)
    @Column(name = "created_at", nullable = false, insertable = false, updatable = false)
    private Instant createdAt;

    /**
     * Generated by the database on insert, then explicitly advanced with the decision timestamp.
     *
     * <p>The schema has no update trigger, so leaving this permanently database-generated would make
     * {@code updated_at} lie after the first decision.
     */
    @Generated(event = EventType.INSERT)
    @Column(name = "updated_at", nullable = false, insertable = false)
    private Instant updatedAt;

    protected ApprovalRequest() {}

    public static ApprovalRequest pending(
            String id,
            String runId,
            String orderId,
            String userId,
            AllowedAction action,
            BigDecimal amount,
            String eligibilityRuleCode,
            String reasonCode,
            Instant expiresAt) {
        Objects.requireNonNull(id, "id");
        Objects.requireNonNull(runId, "runId");
        Objects.requireNonNull(orderId, "orderId");
        Objects.requireNonNull(userId, "userId");
        Objects.requireNonNull(action, "action");
        Objects.requireNonNull(eligibilityRuleCode, "eligibilityRuleCode");
        Objects.requireNonNull(reasonCode, "reasonCode");
        Objects.requireNonNull(expiresAt, "expiresAt");
        if (action != AllowedAction.REFUND_ONLY
                && action != AllowedAction.RETURN
                && action != AllowedAction.RETURN_REFUND) {
            throw new IllegalArgumentException("an approval may bind only an actionable after-sales action");
        }
        boolean movesMoney = action == AllowedAction.REFUND_ONLY || action == AllowedAction.RETURN_REFUND;
        if (movesMoney && amount == null) {
            throw new IllegalArgumentException("a money-moving approval must bind an amount");
        }
        if (!movesMoney && amount != null) {
            throw new IllegalArgumentException("a pure return approval must not bind a refund amount");
        }
        if (amount != null && amount.signum() < 0) {
            throw new IllegalArgumentException("approval amount cannot be negative");
        }

        ApprovalRequest request = new ApprovalRequest();
        request.id = id;
        request.runId = runId;
        request.orderId = orderId;
        request.userId = userId;
        request.action = action;
        request.amount = amount;
        request.status = ApprovalStatus.PENDING;
        request.eligibilityRuleCode = eligibilityRuleCode;
        request.reasonCode = reasonCode;
        request.expiresAt = expiresAt;
        return request;
    }

    public void approve(CommercePrincipal principal, Instant decidedAt) {
        ApprovalAuthorization.requireApprover(principal);
        decide(ApprovalStatus.APPROVED, principal.userId(), decidedAt);
    }

    public void deny(CommercePrincipal principal, Instant decidedAt) {
        ApprovalAuthorization.requireApprover(principal);
        decide(ApprovalStatus.DENIED, principal.userId(), decidedAt);
    }

    /**
     * Expiry is a system transition, not an approver decision. T052 will own how/when it is invoked;
     * T049 only pins that PENDING may become EXPIRED and that EXPIRED is terminal.
     */
    public void expire(Instant expiredAt) {
        decide(ApprovalStatus.EXPIRED, null, expiredAt);
    }

    private void decide(ApprovalStatus target, String actorId, Instant at) {
        Objects.requireNonNull(at, "decision timestamp");
        if (status != ApprovalStatus.PENDING) {
            throw new IllegalStateException("a terminal approval decision cannot be rewritten");
        }
        status = target;
        decidedBy = actorId;
        decidedAt = at;
        updatedAt = at;
    }

    /**
     * Whether this approval was issued for exactly the proposed write.
     *
     * <p>{@link BigDecimal#compareTo(BigDecimal)} is intentional: {@code 500.0} and {@code 500.00}
     * are the same amount even though {@code BigDecimal.equals} would reject the different scale.
     */
    public boolean binds(
            String proposedRunId, String proposedOrderId, AllowedAction proposedAction, BigDecimal proposedAmount) {
        if (!Objects.equals(runId, proposedRunId)
                || !Objects.equals(orderId, proposedOrderId)
                || action != proposedAction) {
            return false;
        }
        if (amount == null || proposedAmount == null) {
            return amount == null && proposedAmount == null;
        }
        return amount.compareTo(proposedAmount) == 0;
    }

    public String getId() {
        return id;
    }

    public String getRunId() {
        return runId;
    }

    public String getOrderId() {
        return orderId;
    }

    public String getUserId() {
        return userId;
    }

    public AllowedAction getAction() {
        return action;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public ApprovalStatus getStatus() {
        return status;
    }

    public String getEligibilityRuleCode() {
        return eligibilityRuleCode;
    }

    public String getReasonCode() {
        return reasonCode;
    }

    public String getDecidedBy() {
        return decidedBy;
    }

    public Instant getDecidedAt() {
        return decidedAt;
    }

    public Instant getExpiresAt() {
        return expiresAt;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}
