-- CommerceAgent T008 - initial core schema
--
-- Boundary rules:
--   * commerce.* is authoritative business state owned by the Java backend.
--   * agent.* stores Agent execution state only.
--   * agent tables intentionally do NOT declare foreign keys into commerce.*.
--   * Policy/vector, refund/return/approval/ticket tables belong to later tasks.

-- -----------------------------------------------------------------------------
-- commerce.users
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.users (
    id          VARCHAR(64)  PRIMARY KEY,
    username    VARCHAR(100) NOT NULL UNIQUE,
    role        VARCHAR(20)  NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_users_role
        CHECK (role IN ('CUSTOMER', 'APPROVER', 'SUPPORT')),
    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'DISABLED'))
);

-- -----------------------------------------------------------------------------
-- commerce.orders
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.orders (
    id                  VARCHAR(64)    PRIMARY KEY,
    user_id             VARCHAR(64)    NOT NULL,
    status              VARCHAR(20)    NOT NULL,
    total_amount        NUMERIC(19, 2) NOT NULL,
    currency            CHAR(3)        NOT NULL,
    created_at          TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    shipped_at          TIMESTAMPTZ,
    delivered_at        TIMESTAMPTZ,
    after_sales_status  VARCHAR(32),
    version             BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES commerce.users(id),
    CONSTRAINT chk_orders_status
        CHECK (status IN ('PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'CLOSED')),
    CONSTRAINT chk_orders_total_amount
        CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_currency
        CHECK (currency = UPPER(currency)),
    CONSTRAINT chk_orders_version
        CHECK (version >= 0),
    CONSTRAINT chk_orders_time_order
        CHECK (
            (shipped_at IS NULL OR shipped_at >= created_at)
            AND (delivered_at IS NULL OR shipped_at IS NULL OR delivered_at >= shipped_at)
        )
);

CREATE INDEX idx_orders_user_id ON commerce.orders(user_id);
CREATE INDEX idx_orders_status ON commerce.orders(status);

-- -----------------------------------------------------------------------------
-- commerce.order_items
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.order_items (
    id                VARCHAR(64)    PRIMARY KEY,
    order_id          VARCHAR(64)    NOT NULL,
    product_id        VARCHAR(64)    NOT NULL,
    product_name      VARCHAR(255)   NOT NULL,
    product_category  VARCHAR(100)   NOT NULL,
    unit_price        NUMERIC(19, 2) NOT NULL,
    quantity          INTEGER        NOT NULL,

    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES commerce.orders(id) ON DELETE CASCADE,
    CONSTRAINT chk_order_items_unit_price
        CHECK (unit_price >= 0),
    CONSTRAINT chk_order_items_quantity
        CHECK (quantity > 0)
);

CREATE INDEX idx_order_items_order_id ON commerce.order_items(order_id);
CREATE INDEX idx_order_items_product_category ON commerce.order_items(product_category);

-- -----------------------------------------------------------------------------
-- commerce.shipments
-- V1 invariant: one order has at most one shipment.
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.shipments (
    id               VARCHAR(64)  PRIMARY KEY,
    order_id         VARCHAR(64)  NOT NULL UNIQUE,
    carrier          VARCHAR(100) NOT NULL,
    tracking_number  VARCHAR(128) NOT NULL,
    status           VARCHAR(32)  NOT NULL,
    last_event_at    TIMESTAMPTZ,
    signed_at        TIMESTAMPTZ,
    version          BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id) REFERENCES commerce.orders(id),
    CONSTRAINT chk_shipments_version
        CHECK (version >= 0),
    CONSTRAINT uq_shipments_carrier_tracking
        UNIQUE (carrier, tracking_number)
);

CREATE INDEX idx_shipments_status ON commerce.shipments(status);

-- -----------------------------------------------------------------------------
-- commerce.logistics_events
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.logistics_events (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id  VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    description  TEXT         NOT NULL,
    occurred_at  TIMESTAMPTZ  NOT NULL,

    CONSTRAINT fk_logistics_events_shipment
        FOREIGN KEY (shipment_id) REFERENCES commerce.shipments(id) ON DELETE CASCADE
);

CREATE INDEX idx_logistics_events_shipment_time
    ON commerce.logistics_events(shipment_id, occurred_at DESC);

-- -----------------------------------------------------------------------------
-- commerce.after_sales_rules
-- Structured deterministic rules used by the Java eligibility service.
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.after_sales_rules (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code                 VARCHAR(100)   NOT NULL,
    version                   INTEGER        NOT NULL,
    product_category          VARCHAR(100),
    required_order_status     VARCHAR(20),
    logistics_stalled_hours   INTEGER,
    return_window_days        INTEGER,
    max_refund_amount         NUMERIC(19, 2),
    approval_threshold        NUMERIC(19, 2),
    allowed_action            VARCHAR(32)    NOT NULL,
    active                    BOOLEAN        NOT NULL DEFAULT TRUE,
    effective_from            TIMESTAMPTZ    NOT NULL,
    effective_to              TIMESTAMPTZ,

    CONSTRAINT uq_after_sales_rules_code_version
        UNIQUE (rule_code, version),
    CONSTRAINT chk_after_sales_rules_version
        CHECK (version > 0),
    CONSTRAINT chk_after_sales_rules_required_status
        CHECK (
            required_order_status IS NULL
            OR required_order_status IN ('PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'CLOSED')
        ),
    CONSTRAINT chk_after_sales_rules_stalled_hours
        CHECK (logistics_stalled_hours IS NULL OR logistics_stalled_hours >= 0),
    CONSTRAINT chk_after_sales_rules_return_window
        CHECK (return_window_days IS NULL OR return_window_days >= 0),
    CONSTRAINT chk_after_sales_rules_max_refund
        CHECK (max_refund_amount IS NULL OR max_refund_amount >= 0),
    CONSTRAINT chk_after_sales_rules_approval_threshold
        CHECK (approval_threshold IS NULL OR approval_threshold >= 0),
    CONSTRAINT chk_after_sales_rules_allowed_action
        CHECK (allowed_action IN ('REFUND_ONLY', 'RETURN', 'RETURN_REFUND', 'MANUAL_REVIEW', 'DENY')),
    CONSTRAINT chk_after_sales_rules_effective_range
        CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE INDEX idx_after_sales_rules_active_category
    ON commerce.after_sales_rules(active, product_category);

-- -----------------------------------------------------------------------------
-- commerce.audit_logs
-- Structured audit only; never hidden chain-of-thought or raw auth tokens.
-- run_id is a logical reference to agent.agent_runs, intentionally without a
-- cross-schema FK so commerce authority does not depend on the Agent schema.
-- -----------------------------------------------------------------------------
CREATE TABLE commerce.audit_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type     VARCHAR(20)  NOT NULL,
    actor_id       VARCHAR(128) NOT NULL,
    action         VARCHAR(100) NOT NULL,
    resource_type  VARCHAR(100) NOT NULL,
    resource_id    VARCHAR(128) NOT NULL,
    run_id         UUID,
    result         VARCHAR(32)  NOT NULL,
    metadata_json  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_audit_logs_actor_type
        CHECK (actor_type IN ('USER', 'AGENT', 'APPROVER', 'SYSTEM'))
);

CREATE INDEX idx_audit_logs_resource
    ON commerce.audit_logs(resource_type, resource_id, created_at DESC);
CREATE INDEX idx_audit_logs_run_id
    ON commerce.audit_logs(run_id) WHERE run_id IS NOT NULL;
CREATE INDEX idx_audit_logs_created_at
    ON commerce.audit_logs(created_at DESC);

-- -----------------------------------------------------------------------------
-- agent.agent_runs
-- Agent execution state. user_id/resolved_order_id are opaque references only;
-- validation of authoritative business state must go through the Java API.
-- -----------------------------------------------------------------------------
CREATE TABLE agent.agent_runs (
    run_id              UUID PRIMARY KEY,
    user_id             VARCHAR(64)  NOT NULL,
    status              VARCHAR(32)  NOT NULL,
    intent              VARCHAR(100),
    resolved_order_id   VARCHAR(64),
    current_node        VARCHAR(100),
    next_action         VARCHAR(100),
    step_count          INTEGER      NOT NULL DEFAULT 0,
    retry_count         INTEGER      NOT NULL DEFAULT 0,
    state_json          JSONB        NOT NULL DEFAULT '{}'::jsonb,
    final_action        VARCHAR(100),
    error_code          VARCHAR(100),
    model_name          VARCHAR(100) NOT NULL,
    model_temperature   NUMERIC(4, 3) NOT NULL DEFAULT 0,
    prompt_version      VARCHAR(64)  NOT NULL,
    input_tokens        INTEGER      NOT NULL DEFAULT 0,
    output_tokens       INTEGER      NOT NULL DEFAULT 0,
    started_at          TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at        TIMESTAMPTZ,

    CONSTRAINT chk_agent_runs_status
        CHECK (status IN (
            'RUNNING', 'WAITING_USER', 'WAITING_APPROVAL', 'COMPLETED',
            'ESCALATED', 'FAILED', 'SAFE_STOP'
        )),
    CONSTRAINT chk_agent_runs_step_count
        CHECK (step_count >= 0),
    CONSTRAINT chk_agent_runs_retry_count
        CHECK (retry_count >= 0),
    CONSTRAINT chk_agent_runs_model_temperature
        CHECK (model_temperature >= 0),
    CONSTRAINT chk_agent_runs_input_tokens
        CHECK (input_tokens >= 0),
    CONSTRAINT chk_agent_runs_output_tokens
        CHECK (output_tokens >= 0),
    CONSTRAINT chk_agent_runs_completion_time
        CHECK (completed_at IS NULL OR completed_at >= started_at)
);

CREATE INDEX idx_agent_runs_user_started
    ON agent.agent_runs(user_id, started_at DESC);
CREATE INDEX idx_agent_runs_status
    ON agent.agent_runs(status);
CREATE INDEX idx_agent_runs_resolved_order
    ON agent.agent_runs(resolved_order_id) WHERE resolved_order_id IS NOT NULL;

-- -----------------------------------------------------------------------------
-- agent.tool_executions
-- -----------------------------------------------------------------------------
CREATE TABLE agent.tool_executions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id          UUID         NOT NULL,
    step_index      INTEGER      NOT NULL,
    tool_name       VARCHAR(100) NOT NULL,
    risk_level      VARCHAR(20)  NOT NULL,
    input_summary   JSONB        NOT NULL DEFAULT '{}'::jsonb,
    output_summary  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    status          VARCHAR(20)  NOT NULL,
    error_code      VARCHAR(100),
    retryable       BOOLEAN      NOT NULL DEFAULT FALSE,
    latency_ms      BIGINT       NOT NULL DEFAULT 0,
    trace_id        VARCHAR(128) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_tool_executions_run
        FOREIGN KEY (run_id) REFERENCES agent.agent_runs(run_id) ON DELETE CASCADE,
    CONSTRAINT uq_tool_executions_run_step
        UNIQUE (run_id, step_index),
    CONSTRAINT chk_tool_executions_step_index
        CHECK (step_index >= 0),
    CONSTRAINT chk_tool_executions_risk_level
        CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT chk_tool_executions_status
        CHECK (status IN ('SUCCESS', 'ERROR', 'TIMEOUT', 'DENIED')),
    CONSTRAINT chk_tool_executions_latency
        CHECK (latency_ms >= 0)
);

CREATE INDEX idx_tool_executions_run_created
    ON agent.tool_executions(run_id, created_at);
CREATE INDEX idx_tool_executions_trace_id
    ON agent.tool_executions(trace_id);
