-- -----------------------------------------------------------------------------
-- V002 — Agent run resume arbitration + checkpoint history (T017)
--
-- Why this migration exists
-- -------------------------
-- V001 created `agent.agent_runs` and `agent.tool_executions`, but a run row is not yet a
-- *checkpoint*: it has no concurrency token, no checkpoint history, and no way to record that its
-- detailed payload was retired. T017 has to answer three questions that V001's schema cannot:
--
--   1. **Two requests resume the same WAITING_APPROVAL checkpoint. How many may proceed?** Exactly
--      one. `SELECT ... FOR UPDATE` alone serialises them but does not detect the second one's stale
--      read -- it would block, wake up, and happily write a state derived from a checkpoint that no
--      longer exists. A version column is what turns "I read a row" into "I read *that* row", so the
--      second writer's UPDATE matches zero rows instead of forking execution.
--
--   2. **Where does a checkpoint live?** `state_json` is the row's queryable projection of the
--      current state, and it can be cleared by retention. History -- what the state was at each
--      step, so a failed run can be reconstructed -- needs its own table, or "this run was resumed
--      from the state it had at step 3" cannot be demonstrated.
--
--   3. **How does a terminal run stop growing without losing the evidence?** Retention clears
--      `state_json` (large) and old tool traces, but must *record* that it did, and must leave a
--      minimal failure signature behind. `checkpoint_compacted_at` is that record.
--
-- Nothing here is a business authorization: `agent_runs.status` still grants no permission. See
-- `specs/002-commerce-after-sales-agent/data-model.md` section 12 and the T015/T017 rules.
-- -----------------------------------------------------------------------------

-- -----------------------------------------------------------------------------
-- agent.agent_runs — concurrency token, retention marker, status widened to V001's own list
-- -----------------------------------------------------------------------------

-- The compare-and-swap token. Starts at 1 for existing rows so "no version yet" is not a state any
-- reader has to special-case, and NOT NULL so a write that forgets it fails loudly.
ALTER TABLE agent.agent_runs
    ADD COLUMN version INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN checkpoint_compacted_at TIMESTAMPTZ;

ALTER TABLE agent.agent_runs
    ADD CONSTRAINT chk_agent_runs_version
        CHECK (version >= 1);

-- A resumed run has a completed_at; a waiting one does not. V001 allowed completed_at to be set
-- while status was still RUNNING, which is a contradiction retention cannot act on (it keys on
-- "terminal"), so bind the two together. Existing V001 rows satisfy this by construction.
ALTER TABLE agent.agent_runs
    ADD CONSTRAINT chk_agent_runs_terminal_has_completion
        CHECK (
            (status IN ('COMPLETED', 'ESCALATED', 'FAILED', 'SAFE_STOP')) = (completed_at IS NOT NULL)
        );

-- Retention scans "terminal runs older than a cutoff" and "waiting runs untouched for a long time",
-- both keyed on status + started_at. The V001 index on status alone cannot serve the range.
CREATE INDEX idx_agent_runs_status_started
    ON agent.agent_runs(status, started_at);

-- -----------------------------------------------------------------------------
-- agent.agent_checkpoints
--
-- One row per (run, version). Written in the *same transaction* as the run row update, so a
-- checkpoint can never describe a state the run row disagrees with -- which is exactly the drift
-- ("row says COMPLETED, payload still RUNNING") that data-model.md section 12 forbids.
--
-- The payload is the AgentState JSON and is therefore subject to the same fail-closed secret guard
-- as `state_json`. This table is the reason the guard is a *persistence boundary* rule rather than a
-- field decorator: it is a second write target for the same data.
-- -----------------------------------------------------------------------------
CREATE TABLE agent.agent_checkpoints (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                 UUID        NOT NULL,
    version                INTEGER     NOT NULL,
    status                 VARCHAR(32) NOT NULL,
    current_node           VARCHAR(100),
    next_action            VARCHAR(100),
    step_count             INTEGER     NOT NULL DEFAULT 0,
    retry_count            INTEGER     NOT NULL DEFAULT 0,
    state_json             JSONB       NOT NULL DEFAULT '{}'::jsonb,
    reason_code            VARCHAR(100),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_agent_checkpoints_run
        FOREIGN KEY (run_id) REFERENCES agent.agent_runs(run_id) ON DELETE CASCADE,
    CONSTRAINT uq_agent_checkpoints_run_version
        UNIQUE (run_id, version),
    CONSTRAINT chk_agent_checkpoints_version
        CHECK (version >= 1),
    CONSTRAINT chk_agent_checkpoints_status
        CHECK (status IN (
            'RUNNING', 'WAITING_USER', 'WAITING_APPROVAL', 'COMPLETED',
            'ESCALATED', 'FAILED', 'SAFE_STOP'
        )),
    CONSTRAINT chk_agent_checkpoints_step_count
        CHECK (step_count >= 0),
    CONSTRAINT chk_agent_checkpoints_retry_count
        CHECK (retry_count >= 0)
);

-- Resume reads the newest checkpoint for a run; the unique constraint above already orders
-- (run_id, version), so this index only has to make the ordered scan cheap on large runs.
CREATE INDEX idx_agent_checkpoints_run_created
    ON agent.agent_checkpoints(run_id, created_at DESC);
