package com.seventeen17.commerceagent.logistics;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * `commerce.logistics_events` —— 追加式的物流事件记录。
 *
 * <p>与 `order_items` 的差别正是聚合边界的体现：
 *
 * <ul>
 *   <li>`order_items` 属于订单聚合 —— 建订单时一起写、删订单时一起删（V001 里是 `ON DELETE CASCADE`），所以
 *       `Order` 上有 `@OneToMany(cascade = ALL, orphanRemoval = true)`。
 *   <li>`logistics_events` 是**追加式的事实记录**，生命周期独立、按时间查询（"最近一次有效事件"是停滞判定的输入），
 *       所以不在 `Shipment` 上挂集合，而是用仓储查询取最近一条，避免为了算停滞时长而把全部事件加载进内存。
 * </ul>
 *
 * <p>类型映射注意：
 *
 * <ul>
 *   <li>`id` 是 `BIGINT GENERATED BY DEFAULT AS IDENTITY`，是全项目少见的数据库自增主键，因此需要
 *       {@code @GeneratedValue(IDENTITY)}；其余实体的 id 都由应用分配。
 *   <li>`description` 在 V001 里是 `TEXT`，而 Hibernate 默认把 String 当 `varchar(255)`，`ddl-auto: validate`
 *       会因此启动失败，所以显式声明 {@code @JdbcTypeCode(SqlTypes.LONGVARCHAR)}（PostgreSQL 方言下即 `text`）。
 * </ul>
 */
@Entity
@Table(name = "logistics_events")
public class LogisticsEvent {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "shipment_id", nullable = false, updatable = false)
    private Shipment shipment;

    @Column(name = "event_type", length = 64, nullable = false)
    private String eventType;

    @JdbcTypeCode(SqlTypes.LONGVARCHAR)
    @Column(name = "description", nullable = false)
    private String description;

    @Column(name = "occurred_at", nullable = false)
    private Instant occurredAt;

    protected LogisticsEvent() {}

    public static LogisticsEvent create(Shipment shipment, String eventType, String description, Instant occurredAt) {
        LogisticsEvent event = new LogisticsEvent();
        event.shipment = shipment;
        event.eventType = eventType;
        event.description = description;
        event.occurredAt = occurredAt;
        return event;
    }

    public Long getId() {
        return id;
    }

    /** 只返回运单 id，不暴露 {@code Shipment} 引用（理由同 OrderItem）。 */
    public String getShipmentId() {
        return shipment == null ? null : shipment.getId();
    }

    public String getEventType() {
        return eventType;
    }

    public String getDescription() {
        return description;
    }

    public Instant getOccurredAt() {
        return occurredAt;
    }
}
